
create role anon; create role authenticated; create role service_role;
grant usage on schema public to anon,authenticated,service_role;
create schema auth; create table auth.users(id uuid primary key);
create type public.exercise_type as enum('weight','other','speed','time');
create table public.exercises(id bigint generated by default as identity primary key,name text not null,description text,howto text,categoryid bigint not null default 1,type public.exercise_type not null,public boolean not null default false,userid uuid,created_at timestamptz default now());
create table public.exercisemuscles(exerciseid bigint references exercises(id),muscleid bigint,primary key(exerciseid,muscleid));
create table public.workouts(id bigint generated by default as identity primary key,name text not null,status text not null,userid uuid not null,created_at timestamptz default now(),finished_at timestamptz);
create table public.workout_items(id bigint generated by default as identity primary key,exerciseid bigint references exercises(id),position integer,workout bigint references workouts(id),is_finished boolean);
create table public.sets(id bigint generated by default as identity primary key,userid uuid,workout_id bigint references workouts(id),workout_item_id bigint references workout_items(id),position integer,type text,is_finished boolean,weight numeric,reps integer,speed numeric,distance numeric);

create table public.exercise_categories(id bigint primary key,name text);
create table public.muscles(id bigint primary key,name text);
insert into public.exercise_categories values(1,'Kraft');

create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema auth to anon,authenticated;
grant execute on function auth.uid() to authenticated;
grant all on workouts,workout_items,sets,exercises,exercisemuscles to authenticated;
grant usage on all sequences in schema public to authenticated;
alter table workouts enable row level security;
alter table workout_items enable row level security;
alter table sets enable row level security;
alter table exercises enable row level security;
-- Deliberately permissive baseline: new restrictive policies must still reject invalid writes.
create policy fixture_all on workouts to authenticated using(true) with check(true);
create policy fixture_all on workout_items to authenticated using(true) with check(true);
create policy fixture_all on sets to authenticated using(true) with check(true);
create policy fixture_all on exercises to authenticated using(true) with check(true);

create function public.fn_remove_unfinished_sets_and_empty_workout_items() returns trigger language plpgsql as $$
begin
 if new.status='finished' and old.status!='finished' then
  delete from sets using workout_items where sets.workout_item_id=workout_items.id and workout_items.workout=new.id and sets.is_finished=false;
  delete from workout_items where workout=new.id and not exists(select 1 from sets where sets.workout_item_id=workout_items.id);
 end if;
 return new;
end $$;
create trigger trg_remove_unfinished_sets_and_empty_workout_items after update on workouts for each row execute function fn_remove_unfinished_sets_and_empty_workout_items();
